Cherry pick of d8c7269786cb080db7970feae0840c674e698024 failed
stdout:
Auto-merging content/developer/howtos.rst
CONFLICT (content): Merge conflict in content/developer/howtos.rst
CONFLICT (modify/delete): content/developer/howtos/provide_iap_services.rst deleted in d8c726978 ([IMP] iap: remove documentation related to IAP services creation) and modified in HEAD.  Version HEAD of content/developer/howtos/provide_iap_services.rst left in tree.
Auto-merging redirects/14.0.txt

stderr:
18:00:08.698012 git.c:463               trace: built-in: git cherry-pick d8c7269786cb080db7970feae0840c674e698024
error: could not apply d8c726978... [IMP] iap: remove documentation related to IAP services creation
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: